version: "3.2"

services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: db
      POSTGRES_USER: rus2m
      POSTGRES_PASSWORD:
    ports:
      - 5432:5432